var username;
var myName="Aliza Muhammad Zahid";
alert(myName);
var message="Hello World";
alert(message);
var studentName="Jhone Doe";
alert(studentName);
var studentAge="15 years old";
alert(studentAge);
var studentCourse="Certifief Mobile Application & Development";
alert(studentCourse);
var pizza="PIZZA\nPIZZ\nPIZ\nPI\nP";
alert(pizza);
var em="my email address is ";
var addr="alizamuhammadzahid@gmail.com";
alert(em+addr);
var book="i'm trying to learn from the Book";
var ref=" A smarter way to learn JavaScript.";
var full=book+ref;
alert(full);
document.writeln("YAH! I can write HTML content through JAVASCRIPT\n");
document.writeln("<br>-------------------------------------");
var symbols="▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬";
alert(symbols);
document.writeln("<br>▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬");
document.writeln("<br>-------------------------------------");